// react-sample/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [fullName, setFullName] = useState('');
  const [renderFullName, setToRenderFullName] = useState('');

  const webview = {
    listenerFromNative: function(payload) {
      setToRenderFullName(payload);
    }
  };

  useEffect(() => {
    window.webview = webview
  });

  const handleChange = (e) => {
    setFullName(e.target.value);
  };

  const submit = (e) => {
    e.preventDefault();

    if (fullName) {
      if (window.webkit) {
        return window.webkit.messageHandlers.sampleFunction.postMessage(fullName);
      }
    }
  };

  return (
    <div className="App">
      <header className="text-center">React App</header>

      <form className="text-center" id="form">
        <input
          type="text"
          placeholder="Full Name"
          id="full-name"
          onChange={ handleChange }
        />

        <button onClick={ submit }>Submit</button>
      </form>

      <div id="container" className="text-center">
        <div id="text-full-name">
          <small>Full Name:</small>

          <h2>{ renderFullName }</h2>
        </div>
      </div>
    </div>
  );
}

export default App;

// vue-sample/src/App.vue
<template>
  <div id="app">
    <header class="text-center">Vue App</header>

    <form class="text-center" id="form">
      <input
        type="text"
        placeholder="Full Name"
        id="full-name"
        v-model="fullName"
      />

      <button @click.prevent="onSubmit">Submit</button>
    </form>

    <div id="container" class="text-center">
      <div id="text-full-name">
        <small>Full Name:</small>

        <h2>{{ dataFromNative }}</h2>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',

  data() {
    return {
      fullName: '',
      dataFromNative: ''
    }
  },

  mounted() {
    window.webview = this
  },

  methods: {
    onSubmit() {
      if (this.fullName) {
        if (window.webkit) {
          return window.webkit.messageHandlers.sampleFunction
            .postMessage(this.fullName)
        }
      }
    },

    listenerFromNative(payload) {
      this.dataFromNative = payload
    }
  }
}
</script>

<style></style>
