// angular-sample/src/app/app.component.ts
import { Component, OnInit, NgZone } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  public fullName = '';

  profileForm = new FormGroup({
    fullName: new FormControl('')
  });

  constructor(private ngZone: NgZone) {}

  onSubmit() {
    const frm = this.profileForm.value;
    const fullNameVal = frm.fullName;

    if (fullNameVal) {
      if ((window as any).webkit) {
        return (window as any).webkit.messageHandlers.sampleFunction.postMessage(fullNameVal);
      }
    }
  }

  listenerFromNative(payload: string) {
    this.ngZone.run(() => {
      this.fullName = payload;
    });
  }

  ngOnInit() {
    (window as any).webview = this;
  }
}

<header class="text-center">Angular App</header>

<form [formGroup]="profileForm" class="text-center" (ngSubmit)="onSubmit()">
  <input
    type="text"
    placeholder="Full Name"
    id="full-name"
    formControlName="fullName" />

  <button>Submit</button>
</form>

<div id="container" class="text-center">
  <div id="text-full-name">
    <small>Full Name:</small>

    <h2>{{ fullName }}</h2>
  </div>
</div>

// react-sample/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [fullName, setFullName] = useState('');
  const [renderFullName, setToRenderFullName] = useState('');

  const webview = {
    listenerFromNative: function(payload) {
      setToRenderFullName(payload);
    }
  };

  useEffect(() => {
    window.webview = webview
  });

  const handleChange = (e) => {
    setFullName(e.target.value);
  };

  const submit = (e) => {
    e.preventDefault();

    if (fullName) {
      if (window.webkit) {
        return window.webkit.messageHandlers.sampleFunction.postMessage(fullName);
      }
    }
  };

  return (
    <div className="App">
      <header className="text-center">React App</header>

      <form className="text-center" id="form">
        <input
          type="text"
          placeholder="Full Name"
          id="full-name"
          onChange={ handleChange }
        />

        <button onClick={ submit }>Submit</button>
      </form>

      <div id="container" className="text-center">
        <div id="text-full-name">
          <small>Full Name:</small>

          <h2>{ renderFullName }</h2>
        </div>
      </div>
    </div>
  );
}

export default App;
